Plugins.link("clipboardEx.dll");

//----------------------------------------------------------------------
// キャンバス
//
// マウス左ドラッグで黒、右ドラッグで白の矩形を描画
//----------------------------------------------------------------------
class CanvasLayer extends Layer
{
  var dragging = void;
  var draggingButton;

  function CanvasLayer {
    super.Layer(...);
    setSize(300, 300);
    fillRect(0, 0, width, height, 0xFFFFFFFF);
    visible = true;
  }

  function onMouseDown(x, y, button) {
    if (button == mbLeft 
        || button == mbRight) {
      dragging = true;
      draggingButton = button;
      drawPen(x, y);
    }
  }

  function onMouseMove(x, y) {
    if (dragging) 
      drawPen(x, y);
  }

  function onMouseUp {
    dragging = false;
  }

  function drawPen(x, y) {
    fillRect(x - 10, y - 10, 20, 20, draggingButton == mbLeft ? 0xFF000000 : 0xFFFFFFFF);
  }
}

//----------------------------------------------------------------------
// テストアプリ
//----------------------------------------------------------------------
class AppWindow extends Window
{
  var editMenuItem;
  var copyMenuItem;
  var pasteMenuItem;
  var toggleAutoPasteMenuItem;
  var canvas;

  // コンストラクタ
  function AppWindow {
    super.Window();

    // ウィンドウ初期化
    System.title = caption = "クリップボードテスト";
    borderStyle = bsSingle;
    showScrollBars = false;

    // レイヤ作成
    canvas = new CanvasLayer(this, null);
    setInnerSize(canvas.width, canvas.height);
    add(canvas);

    // メニュー生成
    editMenuItem = new MenuItem(this, "編集");
    menu.add(editMenuItem);
    copyMenuItem = new MenuItem(this, "コピー");
    copyMenuItem.onClick = this.onCopy;
    copyMenuItem.shortcut = "Ctrl+C";
    editMenuItem.add(copyMenuItem);
    pasteMenuItem = new MenuItem(this, "ペースト");
    pasteMenuItem.onClick = this.onPaste;
    pasteMenuItem.shortcut = "Ctrl+V";
    editMenuItem.add(pasteMenuItem);
    editMenuItem.add(new MenuItem(this, "-"));
    toggleAutoPasteMenuItem = new MenuItem(this, "自動更新");
    toggleAutoPasteMenuItem.onClick = this.onToggleAutoPaste;
    editMenuItem.add(toggleAutoPasteMenuItem);

    visible = true;
  }

  // キャンバスの内容をクリップボードへコピー
  function onCopy {
    Clipboard.setAsBitmap(canvas);
  }

  // キャンバスの内容をクリップボードからペースト
  function onPaste {
    if (Clipboard.getAsBitmap(canvas)) {
      setInnerSize(canvas.width, canvas.height);
    }
  }

  // 自動更新のトグル
  function onToggleAutoPaste {
    toggleAutoPasteMenuItem.checked = ! toggleAutoPasteMenuItem.checked;
    if (toggleAutoPasteMenuItem.checked)
      // クリップボードが更新されたら自動的にペーストを試みる
      Clipboard.addContentChangeHandler(this.onPaste);
    else
      // 自動更新を解除
      Clipboard.removeContentChangeHandler(this.onPaste);
  }
}


// テストアプリ起動    
var app = new AppWindow();
