"-- Kirikiri V8 Javascript Plugin ---\n"
"\n"
"Node's license follows:\n"
"====\n"
"\n"
"Copyright Joyent, Inc. and other Node contributors. All rights reserved.\n"
"Permission is hereby granted, free of charge, to any person obtaining a copy\n"
"of this software and associated documentation files (the \"Software\"), to\n"
"deal in the Software without restriction, including without limitation the\n"
"rights to use, copy, modify, merge, publish, distribute, sublicense, and/or\n"
"sell copies of the Software, and to permit persons to whom the Software is\n"
"furnished to do so, subject to the following conditions:\n"
"\n"
"The above copyright notice and this permission notice shall be included in\n"
"all copies or substantial portions of the Software.\n"
"\n"
"THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
"IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
"FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
"AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
"LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n"
"FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS\n"
"IN THE SOFTWARE.\n"
"\n"
"\n"
"-- V8 LICENSE FILE --\n"
"This license applies to all parts of V8 that are not externally\n"
"maintained libraries.  The externally maintained libraries used by V8\n"
"are:\n"
"\n"
"  - PCRE test suite, located in\n"
"    test/mjsunit/third_party/regexp-pcre.js.  This is based on the\n"
"    test suite from PCRE-7.3, which is copyrighted by the University\n"
"    of Cambridge and Google, Inc.  The copyright notice and license\n"
"    are embedded in regexp-pcre.js.\n"
"\n"
"  - Layout tests, located in test/mjsunit/third_party.  These are\n"
"    based on layout tests from webkit.org which are copyrighted by\n"
"    Apple Computer, Inc. and released under a 3-clause BSD license.\n"
"\n"
"  - Strongtalk assembler, the basis of the files assembler-arm-inl.h,\n"
"    assembler-arm.cc, assembler-arm.h, assembler-ia32-inl.h,\n"
"    assembler-ia32.cc, assembler-ia32.h, assembler-x64-inl.h,\n"
"    assembler-x64.cc, assembler-x64.h, assembler-mips-inl.h,\n"
"    assembler-mips.cc, assembler-mips.h, assembler.cc and assembler.h.\n"
"    This code is copyrighted by Sun Microsystems Inc. and released\n"
"    under a 3-clause BSD license.\n"
"\n"
"  - Valgrind client API header, located at third_party/valgrind/valgrind.h\n"
"    This is release under the BSD license.\n"
"\n"
"These libraries have their own licenses; we recommend you read them,\n"
"as their terms may differ from the terms below.\n"
"\n"
"Copyright 2014, the V8 project authors. All rights reserved.\n"
"Redistribution and use in source and binary forms, with or without\n"
"modification, are permitted provided that the following conditions are\n"
"met:\n"
"\n"
"    * Redistributions of source code must retain the above copyright\n"
"      notice, this list of conditions and the following disclaimer.\n"
"    * Redistributions in binary form must reproduce the above\n"
"      copyright notice, this list of conditions and the following\n"
"      disclaimer in the documentation and/or other materials provided\n"
"      with the distribution.\n"
"    * Neither the name of Google Inc. nor the names of its\n"
"      contributors may be used to endorse or promote products derived\n"
"      from this software without specific prior written permission.\n"
"\n"
"THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
"\"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
"LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
"A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT\n"
"OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
"SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
"LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
"DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
"THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
"(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
"OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
"\n"
