// レイヤ重ね合わせのストレステスト

class TestWindow extends Window
{
	var fore; // プライマリ
	var layers = []; // レイヤ

	function TestWindow()
	{
		super.Window(...);

		setInnerSize(640, 480);

		add(fore = new Layer(this, null));

		for(var i = 0; i < 100; i++)
		{
			add(layers[i] = new Layer(this, fore));
			layers[i].setImageSize(200, 200);
			layers[i].setSizeToImageSize();
			layers[i].fillRect(0, 0, 200, 200, 0x8000ff00);
			layers[i].visible = true;
		}

		fore.loadImages("../kag3/bgimage/_24_3");
		fore.setSizeToImageSize();

		visible = true;

	}

	function finalize()
	{
		super.finalize(...);
	}

	function action(ev)
	{
		if(ev.target == this && ev.type == "onClick")
		{
			for(var i = 0; i < 100; i++)
			{
				layers[i].setPos(Math.random() * 600, Math.random() * 300);
			}
		}
	}

}

var a = new TestWindow();

