/**
 * 擬似コードによるマニュアル
 *
 * Copyright 2007 GoWatanabe
 */
class Storages {
	/**
	 * ファイル属性の取得
	 * @return 属性情報の入った辞書
	 * size: ファイルサイズ
	 * mtime: 更新日時 (Date オブジェクト)
	 * atime: アクセス日時 (Date オブジェクト)
	 * ctime: 作成日時 (Date オブジェクト)
	 */
	function fstat(filename);

	/**
	 * 吉里吉里のストレージ空間中のファイルを抽出する
	 * @param src 保存元ファイル
	 * @param dest 保存先ファイル
	 */
	function exportFile(src, dest);
};
