Plugins.link("layerExSave.dll");

var WIDTH=800;
var HEIGHT=600;

function dm() {
	Debug.message(...);
}

class MyWindow extends Window
{
	var sendmenu;

	var base;
	var layer;
	var savemenu1;
	var savemenu2;
	
	function MyWindow() {
		super.Window();
		menu.add(savemenu1 = new MenuItem(this, "保存1(&S)"));
		menu.add(savemenu2 = new MenuItem(this, "保存2(&S)"));
		setInnerSize(WIDTH, HEIGHT);

		// プライマリレイヤ
		base = new Layer(this, null);
		base.setSize(WIDTH, HEIGHT);
		base.fillRect(0,0,WIDTH,HEIGHT,0xff000000);
		add(base);

		// 表示レイヤ
		layer = new Layer(this, base);
		layer.setSize(WIDTH, HEIGHT);
		layer.setPos(0, 0);
		layer.visible = true;
		add(layer);

		layer.fillRect(0,0,200,20,0xffff00ff);
		layer.drawText(10, 30, "テストのテキスト", 0xffffff);
	}

	// 実行部
	function action(ev)	{
		if(ev.type == "onClick") {
			if (ev.target == savemenu1) {
				layer.saveLayerImageTlg5("test.tlg");
				layer.saveLayerImageTlg5("test2.tlg", %[xoff:layer.left, yoff:layer.top]);
			} else if (ev.target == savemenu2) {
				startSaveLayerImage(layer, "test3.tlg", %[xoff:layer.left, yoff:layer.top]);
			}
		}
	}

	function onSaveLayerImageProgress(handler, progress, layer, filename) {
		dm(handler + ":" + filename + ":" + progress + "%");
	}

	function onSaveLayerImageDone(handler, canceled, layer, filename) {
		System.inform(handler + ":" + filename + ":" + (canceled ? "canceled" : "done"));
	}
};

var win = new MyWindow();
win.visible = true;
