#pragma once

#include "tjsCommHead.h"

#ifndef TVP_MSG_DECL
	#define TVP_MSG_DECL_NULL(name) extern const tjs_char* name;
#endif

TVP_MSG_DECL_NULL(TVPFaildToCreateDirect3D)
TVP_MSG_DECL_NULL(TVPFaildToDecideBackbufferFormat)
TVP_MSG_DECL_NULL(TVPFaildToCreateDirect3DDevice)
TVP_MSG_DECL_NULL(TVPFaildToSetViewport)
TVP_MSG_DECL_NULL(TVPFaildToSetRenderState)
TVP_MSG_DECL_NULL(TVPWarningImageSizeTooLargeMayBeCannotCreateTexture)
TVP_MSG_DECL_NULL(TVPUsePowerOfTwoSurface)
TVP_MSG_DECL_NULL(TVPCannotAllocateD3DOffScreenSurface)
TVP_MSG_DECL_NULL(TVPBasicDrawDeviceFailedToCreateDirect3DDevices)
TVP_MSG_DECL_NULL(TVPBasicDrawDeviceFailedToCreateDirect3DDevicesUnknownReason)
TVP_MSG_DECL_NULL(TVPBasicDrawDeviceTextureHasAlreadyBeenLocked)
TVP_MSG_DECL_NULL(TVPInternalErrorResult)
TVP_MSG_DECL_NULL(TVPBasicDrawDeviceInfPolygonDrawingFailed)
TVP_MSG_DECL_NULL(TVPBasicDrawDeviceInfDirect3DDevicePresentFailed)

TVP_MSG_DECL_NULL(TVPBasicDrawDeviceFailedToCreateDirect3DDevice)
TVP_MSG_DECL_NULL(TVPBasicDrawDeviceFailedToCreateDirect3DDeviceUnknownReason)

TVP_MSG_DECL_NULL(TVPBasicDrawDeviceDoesNotSupporteLayerManagerMoreThanOne)

TVP_MSG_DECL_NULL(TVPInfoDirect3D)
TVP_MSG_DECL_NULL(TVPCannotLoadD3DDLL)
TVP_MSG_DECL_NULL(TVPNotFoundDirect3DCreate)

TVP_MSG_DECL_NULL(TVPCannotInitDirect3D)

TVP_MSG_DECL_NULL(TVPD3dErrDeviceLost)
TVP_MSG_DECL_NULL(TVPD3dErrDriverIinternalError)
TVP_MSG_DECL_NULL(TVPD3dErrInvalidCall)
TVP_MSG_DECL_NULL(TVPD3dErrOutOfVideoMemory)
TVP_MSG_DECL_NULL(TVPD3dErrOutOfMemory)
TVP_MSG_DECL_NULL(TVPD3dErrWrongTextureFormat)
TVP_MSG_DECL_NULL(TVPD3dErrUnsuportedColorOperation)
TVP_MSG_DECL_NULL(TVPD3dErrUnsuportedColorArg)
TVP_MSG_DECL_NULL(TVPD3dErrUnsuportedAalphtOperation)
TVP_MSG_DECL_NULL(TVPD3dErrUnsuportedAlphaArg)
TVP_MSG_DECL_NULL(TVPD3dErrTooManyOperations)
TVP_MSG_DECL_NULL(TVPD3dErrConflictioningTextureFilter)
TVP_MSG_DECL_NULL(TVPD3dErrUnsuportedFactorValue)
TVP_MSG_DECL_NULL(TVPD3dErrConflictioningRenderState)
TVP_MSG_DECL_NULL(TVPD3dErrUnsupportedTextureFilter)
TVP_MSG_DECL_NULL(TVPD3dErrConflictioningTexturePalette)
TVP_MSG_DECL_NULL(TVPD3dErrNotFound)
TVP_MSG_DECL_NULL(TVPD3dErrMoreData)
TVP_MSG_DECL_NULL(TVPD3dErrDeviceNotReset)
TVP_MSG_DECL_NULL(TVPD3dErrNotAvailable)
TVP_MSG_DECL_NULL(TVPD3dErrInvalidDevice)
TVP_MSG_DECL_NULL(TVPD3dErrDriverInvalidCall)
TVP_MSG_DECL_NULL(TVPD3dErrWasStillDrawing)
TVP_MSG_DECL_NULL(TVPD3dErrDeviceHung)
TVP_MSG_DECL_NULL(TVPD3dErrUnsupportedOverlay)
TVP_MSG_DECL_NULL(TVPD3dErrUnsupportedOverlayFormat)
TVP_MSG_DECL_NULL(TVPD3dErrCannotProtectContent)
TVP_MSG_DECL_NULL(TVPD3dErrUnsupportedCrypto)
TVP_MSG_DECL_NULL(TVPD3dErrPresentStatisticsDisJoint)
TVP_MSG_DECL_NULL(TVPD3dErrDeviceRemoved)
TVP_MSG_DECL_NULL(TVPD3dOkNoAutoGen)
TVP_MSG_DECL_NULL(TVPD3dErrFail)
TVP_MSG_DECL_NULL(TVPD3dErrInvalidArg)
TVP_MSG_DECL_NULL(TVPD3dUnknownError)

