// affineCopy 等のテスト

function intrandom(min = 0, max = 0) 
{
	if(min>max) { var t=max; max=min; min=t; }
	return int(Math.random() * (max-min+1)) + min;
}

class TestWindow extends Window
{
	var fore; // プライマリ
	var src; // レイヤ その1
	var src2; // レイヤその2

	function TestWindow()
	{
		super.Window(...);

		setInnerSize(640, 480);

		add(fore = new Layer(this, null));
		add(src = new Layer(this, fore));
		add(src2 = new Layer(this, fore));

		fore.loadImages("../../../kag3/tests/bgimage/_24_3");
		fore.setSizeToImageSize();
		src.loadImages ("../../../../tlg4comp/b2.bmp");
//		src.loadImages("../kag3/bgimage/black");
		src.setSizeToImageSize();
		src.type = ltCoverRect;
		src2.loadImages("../../../kag3/tests/fgimage/uni");
		src2.setSizeToImageSize();
		src2.type = ltAddAlpha;
		src2.face = dfAddAlpha;
		src2.convertType(dfAlpha);

//		System.addContinuousHandler(process);

		visible = true;

		fore.face = dfOpaque;
//		fore.setClip(200, 100, 200, 200);
//		fore.colorRect(200, 100, 200, 200, 0xff0000, 128);

		fore.face = dfBoth;
/*
		src.face = dfOpaque;
		src.font.height = 30;
		src.fillRect(0, 0, 640, 480, 0);
		src.drawText(100, 200, "文字いっぱい", 0xffffff, 255);
		src.font.height = 16;
		src.drawText(100, 280, "いっぱい文字", 0xffffff, 255);
		src.drawText(100, 310, "いっぱい文字ADFGa;oija;oiergjoiao;aeij", 0xffffff, 255);
*/
		var start = System.getTickCount();
//		for(var i = 0; i < 2000; i++)
//			process5();
//		System.inform(System.getTickCount() - start);


		blt(7.3);
		process6();
	}

	function finalize()
	{
		System.removeContinuousHandler(process);

		super.finalize(...);
	}

	function blt(rad)
	{
		var rad2 = rad + Math.PI / 2;
		var rad3 = rad - Math.PI / 2;
		var xz = 200; //Math.cos(rad*0.45)*500+530;
		var yz = 200; //Math.sin(rad*0.56)*500+530;
		fore.face = dfOpaque;
		fore.holdAlpha = false;
		fore.operateAffine(src, 100, 200, 200, 200, false,
				real(Math.cos(rad) * xz + 320),			real(Math.sin(rad) * yz + 240),
				real(Math.cos(rad2) * xz + 320),		real(Math.sin(rad2) * yz + 240),
				real(Math.cos(rad3) * xz + 320),		real(Math.sin(rad3) * yz + 240),
				omOpaque,
				254,
				/*stNearest*/stFastLinear);
	}

	function process0()
	{
		var rad = System.getTickCount() / 4000;
		var rad2 = rad + Math.PI / 2;
		var rad3 = rad - Math.PI / 2;
		var xz = 200; //Math.cos(rad*0.45)*500+530;
		var yz = 200; //Math.sin(rad*0.56)*500+530;
		fore.face = dfBoth;
		fore.holdAlpha = false;
		fore.affineCopy(src, 100, 200, 200, 200, false,
				real(Math.cos(rad) * xz + 320),			real(Math.sin(rad) * yz + 240),
				real(Math.cos(rad2) * xz + 320),		real(Math.sin(rad2) * yz + 240),
				real(Math.cos(rad3) * xz + 320),		real(Math.sin(rad3) * yz + 240),
				/*stNearest*/stFastLinear);
	}

	function process0o()
	{
		var rad = System.getTickCount() / 4000;
		var rad2 = rad + Math.PI / 2;
		var rad3 = rad - Math.PI / 2;
		var xz = 200; //Math.cos(rad*0.45)*500+530;
		var yz = 200; //Math.sin(rad*0.56)*500+530;
		fore.face = dfOpaque;
		fore.holdAlpha = false;
		fore.operateAffine(src, 100, 200, 200, 200, false,
				real(Math.cos(rad) * xz + 320),			real(Math.sin(rad) * yz + 240),
				real(Math.cos(rad2) * xz + 320),		real(Math.sin(rad2) * yz + 240),
				real(Math.cos(rad3) * xz + 320),		real(Math.sin(rad3) * yz + 240),
				omOpaque,
				8,
				/*stNearest*/stFastLinear);
	}

	function process1()
	{
		var rad = System.getTickCount() / 1100;
		var cos = Math.cos(rad) * Math.sin(rad/3.9) * 2;
		var sin = Math.sin(rad) * Math.sin(rad/3.9) * 2;
		fore.face = dfMain;
//		fore.fillRect(0, 0, fore.imageWidth, fore.imageHeight, 0);
		fore.affinePile(src2, 0, 0, src2.imageWidth, src2.imageHeight, true,
				cos,							sin,
				-sin,							cos,
				320,							240
				);
	}


	function process2()
	{
		var a = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var b = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var c = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var d = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var tx = intrandom(-300, 800);
		var ty = intrandom(-300, 800);
		fore.face = dfBoth;
		fore.affineCopy(src, 0, 0, src.imageWidth, src.imageHeight, true,
				a,								b,
				c,								d,
				tx,								ty
				);
	}

	function process3()
	{
		var a = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var b = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var c = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var d = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var tx = intrandom(-300, 800);
		var ty = intrandom(-300, 800);
		var opa = intrandom(0,1)?255:intrandom(255);
		fore.face = intrandom(0,1)?dfMain:dfBoth;
		fore.affineBlend(src, 0, 0, src.imageWidth, src.imageHeight, true,
				a,								b,
				c,								d,
				tx,								ty,
				opa, stFastLinear, intrandom(0,1));
	}

	function process4()
	{
		var a = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var b = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var c = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var d = intrandom(0, 1) ? Math.random() : Math.random() * 5;
		var tx = intrandom(-300, 800);
		var ty = intrandom(-300, 800);
		var opa = intrandom(0,1)?255:intrandom(255);
		fore.face = intrandom(0,1)?dfMain:dfBoth;
		fore.affinePile(src2, 0, 0, src2.imageWidth, src2.imageHeight, true,
				a,								b,
				c,								d,
				tx,								ty,
				opa, stFastLinear, intrandom(0,1));
	}

	function process5()
	{
		var rad = System.getTickCount() / 2000;
		var rad2 = rad + Math.PI / 2;
		var rad3 = rad - Math.PI / 2;
		fore.face = dfBoth;
		fore.affineBlend(src, 100, 140, 320, 320, false,
				Math.cos(rad) * 200 + 320,		Math.sin(rad) * 200 + 240,
				Math.cos(rad2) * 200 + 320,		Math.sin(rad2) * 200 + 240,
				Math.cos(rad3) * 200 + 320,		Math.sin(rad3) * 200 + 240,
				12,, false);
	}

	function process6()
	{
		var rad = System.getTickCount() / 4000;
		var rad2 = rad + Math.PI / 2;
		var rad3 = rad - Math.PI / 2;
		var xz = 800; //Math.cos(rad*0.45)*500+530;
		var yz = 800; //Math.sin(rad*0.56)*500+530;
		fore.face = dfOpaque;
		fore.holdAlpha = false;
		fore.operateAffine(src2, 0, 0, src2.imageWidth, src2.imageHeight, false,
				real(Math.cos(rad) * xz + 320),			real(Math.sin(rad) * yz + 240),
				real(Math.cos(rad2) * xz + 320),		real(Math.sin(rad2) * yz + 240),
				real(Math.cos(rad3) * xz + 320),		real(Math.sin(rad3) * yz + 240),
				omAddAlpha,
				128,
				/*stNearest*/stFastLinear);
	}

	function process()
	{
		process6();
//		this['process' +intrandom(0, 4)]();
	}
}

var a = new TestWindow();

