/**
 * 擬似コードによるマニュアル
 *
 * Copyright 2007 GoWatanabe
 */
class Storages {
	/**
	 * 署名の確認
	 * @param filename 確認対象ファイル
	 * @param publickey 公開鍵
	 * @param notify 状態通知先オブジェクト
	 * @return -1:中断 0:失敗 1:成功
	 * exe や dll の場合は署名はファイルに内臓されます。xp3 などの場合は、
	 * 元のファイルに .sig をつけた外部ファイルを署名として処理されます。
	 * notify が指定された場合は、進捗の度合いに応じて
	 * notify.onCheckSignatureProgress(percent) が呼び出されます。
	 * percent: 進捗度合い 0～100%
	 * 返り値: true なら継続、false なら中断
	 */
	function checkSignature(filename, publickey, notify=void);

};
