if (typeof global.CSVParser == "undefined") {
	dm("csv Parserr がロードされてない");
	Plugins.link("csvParser.dll");
}

/**
 * シーン定義ファイル読み出し用パーサ
 * キャラ名, コンフィグ名, ボイスファイル名
 */
class VoiceListParser extends CSVParser {

	var voiceInfos = %[]; // ボイス情報
	var check; // ロードチェック用

    /**
     * 行毎に呼び出される
     * @param columns カラムデータ(Array)
     * @param lineNo 論理行番号(1～)
     */
	function doLine(columns, lineNo) {
		if (columns[0].charAt(0) != '#' && columns.count > 0) {
			var name = columns[0].trim();
			if (name != "") {
				var info = voiceInfos[name];
				if (info === void) {
					info = %[];
					voiceInfos[name] = info;
				}
				if (columns.count > 1) {
					info.config   = columns[1].trim();
					info.filename = columns.count > 2 ? columns[2].trim() : "";
				}
			}
		}
    }

	// ファイルをパースする
	function parseStorage(filename,utf8=false) {
		check = false;
		super.parseStorage(...);
		if (check) return;

		// １行も読まれなかったらとりあえずエンコードを変えて読み直し
		super.parseStorage(filename, !utf8);
		if (check) return;

		// それでもダメだったらArrayで読み直す
		var temp = [];
		var sep = (Storages.extractStorageExt(filename).toLowerCase() == ".txt") ? "\t" : ",";
		temp.load(filename);
		for (var i = 0; i < temp.count; i++) {
			var line = [];
			line.split(sep, temp[i]);
			doLine(line, i+1) if (line.count > 0);
		}
	}

	/**
	 * コンストラクタ
	 */
	function VoiceListParser() {
		super.CSVParser(...);
	}
};
