/**
 * 擬似コードによるマニュアル
 */

class Layer {

    /**
     * 明度とコントラスト
     * @param brightness 明度 -255 ～ 255, 負数の場合は暗くなる
     * @param contrast コントラスト -100 ～100, 0 の場合変化しない
     */
    function light(brightness, contrast);
    
    /**
     * 色相と彩度
     * @param hue 色相
     * @param sat 彩度
     * @param blend ブレンド 0 (効果なし) ～ 1 (full effect)
     */
    function colorize(hue, sat, blend);
    
    /**
     * ノイズ追加
     * @param level ノイズレベル 0 (no noise) ～ 255 (lot of noise).
     */
    function noize(level);
};
