Plugins.link("flashPlayer.dll");

var WIDTH=400;
var HEIGHT=200;

function dm() {
	Debug.message(...);
}

/**
 * Flash統合レイヤサンプル
 */
class FlashLayer extends Layer, FlashPlayer
{
	function FlashLayer(window, parent, width, height) {
		global.Layer.Layer(window, parent);
		global.Layer.setSize(width, height);
		global.FlashPlayer.FlashPlayer(width, height);
		hitThreshold = 0;
	}

	// -------------------------------------
	// サイズ変更差し替え
	// -------------------------------------

	function setSize(width, height) {
		global.Layer.setSize(width, height);
		global.FlashPlayer.setSize(width, height);
	}
	
	// -------------------------------------
	// レイヤイベント処理部
	// -------------------------------------

	function onKeyDown(key) {
		dm("キーがおされた:" + key);
		doKeyDown(key);
	}

	function onKeyUp(key) {
		dm("キーがはなされた:" + key);
		doKeyUp(key);
	}

	function onMouseEnter() {
		doMouseEnter();
	}

	function onMouseLeave() {
		doMouseLeave();
	}

	function onMouseDown(x, y, button, shift) {
		doMouseDown(x, y, button, shift);
	}

	function onMouseMove(x, y, shift) {
		doMouseMove(x, y, shift);
	}

	function onMouseUp(x, y, button, shift) {
		doMouseUp(x, y, button, shift);
	}

	function onMouseWheel(shift, delta, x, y) {
		doMouseWheel(shift, delta, x, y);
	}

	function onHitTest(x, y, hit) {
		global.Layer.onHitTest(x, y, hitTest(x, y));
	}
	
	// -------------------------------------
	// Flashイベント処理部
	// -------------------------------------

	function onFrameUpdate() {
		draw(this, true);
	}
	
	function onReadyStateChange(value) {
		dm("state:%s".sprintf(value));
	}
	
	function onProgress(value) {
		dm("progress:%s".sprintf(value));
	}
	
	function onFSCommand(cmd, args) {
		dm("fscommand:%s %s".sprintf(cmd, args));
	}

	// -------------------------------------
	// 呼び出しテスト
	// -------------------------------------

	// ActionScriptから呼ばれるメソッドを定義しておく
	function drawMessage(msg) {
		window.drawMessage(msg);
	}
}

class MyWindow extends Window
{
	var base;
	var layer;
	var layer2;
	var message;
	var exit;
	var red;
	var blue;
	var clear;
	
	function MyWindow() {
		super.Window();
		menu.add(exit = new MenuItem(this, "終了"));
		menu.add(red  = new MenuItem(this, "背景を赤に"));
		menu.add(blue = new MenuItem(this, "背景を青に"));
		menu.add(clear = new MenuItem(this, "clear"));

		setInnerSize(WIDTH, HEIGHT);

		// プライマリレイヤ
		base = new Layer(this, null);
		base.setSize(WIDTH, HEIGHT);
		base.fillRect(0,0,WIDTH,HEIGHT,0xffffffff);
		add(base);
		
		// Flash表示レイヤ
		layer = new FlashLayer(this, base, WIDTH, HEIGHT);
		with (layer) {
			.setPos(0, 0);
			.visible = true;
			.type = ltOpaque;
			.initMovie("test.swf");
		}
		add(layer);
		layer.disableLocalSecurity();
		layer.allowScriptAccess = "always";

		// レイヤにフォーカスをあてる
		layer.enabled = true;
		layer.focusable = true;
		layer.focus(true);
		
		layer2 = new Layer(this, base);
		with (layer2) {
			.setPos(0,0,WIDTH,HEIGHT);
			.fillRect(WIDTH/4,HEIGHT/4,WIDTH/4,HEIGHT/2,0x80ffff00);
			.visible = true;
		}
		add(layer2);

		message = new Layer(this, base);
		with (message) {
			.setPos(0,0,WIDTH,HEIGHT);
			.fillRect(0,0,.width,.height,0);
			.visible = true;
		}
		add(message);

		drawMessage("この文字と黄色の矩形は吉里吉里のレイヤに描画されています");
	}

	// 実行部
	function action(ev)	{
		if(ev.type == "onClick") {
			switch (ev.target) {
			case exit:
				System.terminate();
				break;
			case red:
				// ActionScriptを直接呼び出し
				layer.callFunction("setBaseColor", 0xff0000);
				break;
			case blue:
				// ActionScriptを直接呼び出し
				layer.callFunction("setBaseColor", 0x0000ff);
				break;
			case clear:
				layer.clearMovie();
				break;
			}
		}
	}
	
	// メッセージ描画
	function drawMessage(msg) {
		with (message) {
			.fillRect(0,0,.width,.height,0);
			.drawText(10,10,msg,0x000000,255,true,2,0xffffff);
		}
	}

	function onKeyDown(key) {
		dm("Win:キーがおされた:" + key);
	}
};

var win = new MyWindow();
win.visible = true;
